<div class="jumbotron">
    <h1>Welcome to the <span class="app-orange">command executor</span></h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/MehrAlsNix/interactivephp" target="_blank">interactive-php
            application</a>.
    </p>
</div>
<div class="well-lg">
    <?php
    // within a view script
    /** @var \MehrAlsNix\InteractivePhp\Action\CommandExecutorFormFactory $form */
    $form = $this->form;
    $form->prepare();

    // Assuming the "contact/process" route exists...
    $form->setAttribute('action', $this->url('command-executor'));

    // Set the method attribute for the form
    $form->setAttribute('method', 'post');

    // Get the form label plugin
    /** @var \Zend\Form\View\Helper\FormLabel $formLabel */
    $formLabel = $this->plugin('formLabel');

    // Render the opening tag
    echo $this->form()->openTag($form);
    ?>
    <div class="form_element input-lg">
        <?php
        /** @var \Zend\Form\Element $name */
        $name = $form->get('name');
        echo $formLabel->openTag() . $name->getOption('label');
        echo $this->formInput($name);
        echo $this->formElementErrors($name);
        echo $formLabel->closeTag();
        ?></div>

    <div class="form_element input-lg">
        <?php
        $subject = $form->get('subject');
        echo $formLabel->openTag() . $subject->getOption('label');
        echo $this->formInput($subject);
        echo $this->formElementErrors($subject);
        echo $formLabel->closeTag();
        ?></div>

    <div class="form_element input-lg">
        <?php
        $message = $form->get('message');
        echo $formLabel->openTag() . $message->getOption('label');
        echo $this->formTextarea($message);
        echo $this->formElementErrors($message);
        echo $formLabel->closeTag();
        ?></div>

    <?php echo $this->formElement($form->get('send')) ?>

    <?php echo $this->form()->closeTag() ?>
</div>
