<div class="jumbotron">
    <h1>Welcome to <span class="app-orange">interactive-php</span></h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/MehrAlsNix/interactivephp" target="_blank">interactive-php
            application</a>.
    </p>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="well well-lg">
            <h3>Symfony Command Generator</h3>
            <p>ofwqhrgqooqgoqjgp</p>
            <p><a class="btn btn-primary btn-lg">Learn more</a></p>
        </div>
    </div>
    <div class="col-md-6">
        <div class="well well-lg">
            <h3>Symfony Command Executor</h3>
            <p>Explore the ability to execute your symfony commands.</p>
            <p><a class="btn btn-primary btn-lg" href="<?= $this->url('command-executor') ?>">Try out</a></p>
        </div>
    </div>
</div>
